# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basket_events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'basket_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62\x61sket_events.proto\x12\rbasket.events\x1a\x1fgoogle/protobuf/timestamp.proto\"m\n\x1f\x42\x61sketConfirmedIntegrationEvent\x12\x11\n\tbasket_id\x18\x01 \x01(\t\x12\'\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x16.basket.events.Address\x12\x0e\n\x06volume\x18\x03 \x01(\x05\"\x19\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\"2\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"d\n\x0e\x44\x65liveryPeriod\x12)\n\x05start\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x17Z\x15queues/basketeventspbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basket_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025queues/basketeventspb'
  _globals['_BASKETCONFIRMEDINTEGRATIONEVENT']._serialized_start=71
  _globals['_BASKETCONFIRMEDINTEGRATIONEVENT']._serialized_end=180
  _globals['_ADDRESS']._serialized_start=182
  _globals['_ADDRESS']._serialized_end=207
  _globals['_ITEM']._serialized_start=209
  _globals['_ITEM']._serialized_end=259
  _globals['_DELIVERYPERIOD']._serialized_start=261
  _globals['_DELIVERYPERIOD']._serialized_end=361
# @@protoc_insertion_point(module_scope)
