# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12order_events.proto\x12\x0corder.events\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n\x1cOrderCreatedIntegrationEvent\x12\x10\n\x08order_id\x18\x01 \x01(\t\"F\n\x1eOrderCompletedIntegrationEvent\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\ncourier_id\x18\x02 \x01(\tBS\n\x13queues.order.eventsB\x10OrderEventsProtoZ\x14queues/ordereventspb\xaa\x02\x13Queues.Order.Eventsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023queues.order.eventsB\020OrderEventsProtoZ\024queues/ordereventspb\252\002\023Queues.Order.Events'
  _globals['_ORDERCREATEDINTEGRATIONEVENT']._serialized_start=69
  _globals['_ORDERCREATEDINTEGRATIONEVENT']._serialized_end=117
  _globals['_ORDERCOMPLETEDINTEGRATIONEVENT']._serialized_start=119
  _globals['_ORDERCOMPLETEDINTEGRATIONEVENT']._serialized_end=189
# @@protoc_insertion_point(module_scope)
