# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'geo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgeo.proto\x12\x03geo\"\'\n\x15GetGeolocationRequest\x12\x0e\n\x06street\x18\x01 \x01(\t\" \n\x08Location\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"9\n\x16GetGeolocationResponse\x12\x1f\n\x08location\x18\x01 \x01(\x0b\x32\r.geo.Location2P\n\x03Geo\x12I\n\x0eGetGeolocation\x12\x1a.geo.GetGeolocationRequest\x1a\x1b.geo.GetGeolocationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETGEOLOCATIONREQUEST']._serialized_start=18
  _globals['_GETGEOLOCATIONREQUEST']._serialized_end=57
  _globals['_LOCATION']._serialized_start=59
  _globals['_LOCATION']._serialized_end=91
  _globals['_GETGEOLOCATIONRESPONSE']._serialized_start=93
  _globals['_GETGEOLOCATIONRESPONSE']._serialized_end=150
  _globals['_GEO']._serialized_start=152
  _globals['_GEO']._serialized_end=232
# @@protoc_insertion_point(module_scope)
